jenkinsci/workflow-durable-task-step-plugin

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java

See https://github.com/jenkinsci/workflow-cps-plugin/pull/3 for discussion.
@reviewbybees

[JENKINS-26156] Do not call BodyInvoker.withDisplayName(null)

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

[JENKINS-34281](https://issues.jenkins-ci.org/browse/JENKINS-34281) can mean that if a Pipeline build was running a `node` step but was waiting for an executor (not yet inside the block), after a restart the `Queue.Item` for the block goes missing. Without intervention, the build will just sit there quietly until interrupted.
@reviewbybees

[JENKINS-34281] Better robustness against missing queue items

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/5, https://github.com/jenkinsci/workflow-support-plugin/pull/4, https://github.com/jenkinsci/workflow-job-plugin/pull/5, and https://github.com/jenkinsci/workflow-cps-plugin/pull/20.
@reviewbybees

[JENKINS-26130] Way to print progress from pickles

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Requested by @amuniz in #11.
@reviewbybees

[JENKINS-26133] Display output if script fails

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java

[JENKINS-37121](https://issues.jenkins-ci.org/browse/JENKINS-37121)
The situation described in the issue is anomalous. It is better for `tryResolve` to fail immediately if the workspace was locked by something else, rather than call `acquire` and block a `Timer` thread indefinitely.
@reviewbybees

[JENKINS-37121] Use WorkspaceList.record, not .acquire, when dehydrating a pickle

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

Also improving the display of that behavior a bit.
Was attempting to reproduce a cryptic error from @cyrille-leclerc
```
Resuming build at … after Jenkins restart
Waiting to resume Unknown Pipeline node step: ???
Waiting to resume Unknown Pipeline node step: Waiting for next available executor
Waiting to resume Unknown Pipeline node step: Waiting for next available executor
Waiting to resume Unknown Pipeline node step: Waiting for next available executor
[Pipeline] End of Pipeline
java.io.IOException: Failed to load persisted workflow state
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:585)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:583)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(Cp …
```

Testing behavior when a queue item is canceled while trying to resume a node block

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

@cyrille-leclerc came across a case where due to what seems to be massive corruption of build records on disk for unknown reasons, perhaps combined with https://github.com/jenkinsci/workflow-job-plugin/pull/26, a build was actually marked finished (no master flyweight executor, `ABORTED` status, etc.) yet it had a `PlaceholderExecutable` still occupying an executor slot, which could not be canceled. Inspection in `/script` showed that it was in this clause. Manually calling `.completed(null)` sufficed to clear the executor slot. No idea how to reproduce this situation, but it seems appropriate to do this cleanup.
@reviewbybees

If an executor slot is orphaned, allow it to be manually cleared

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Robustness improvements

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

[JENKINS-41010](https://issues.jenkins-ci.org/browse/JENKINS-41010)
Exposes underlying StepContext from PlaceholderTask.

[JENKINS-41010] Expose StepContext from PlaceholderTask

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

[JENKINS-41339](https://issues.jenkins-ci.org/browse/JENKINS-41339)
Buggy `sh` behavior corrected in `durable-task` 1.13 exposed a bug in the `node` step.
@reviewbybees

[JENKINS-41339] durable-task 1.13 broke an EnvironmentVariablesNodeProperty use case

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

From an installation running with the latest [JENKINS-34021](https://issues.jenkins-ci.org/browse/JENKINS-34021) fixes, get repeated warnings in the log:
```
WARNING	o.j.p.w.s.d.DurableTaskStep$Execution#logger: JENKINS-34021: could not get TaskListener in CpsStepContext[…:sh]:Owner[… #…]java.io.IOException: cannot find current thread
at org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:295)
at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:61)
at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.logger(DurableTaskStep.java:208)
at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.access$700(DurableTaskStep.java:138)
at …
```

[JENKINS-34021] If the step is badly broken, just try to cancel the timer

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

[JENKINS-41446](https://issues.jenkins-ci.org/browse/JENKINS-41446)
I took the EnvStep as example to use the EnvironmentExpander.
As we have only one variable to set, I made ExpanderImpl a bit simpler.
Created unitary tests, including test of NODE_NAME since my first attempt resulted in the variable set to null in the ws step.

[JENKINS-41446] fix $WORKSPACE in ws step

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

https://github.com/jenkinsci/workflow-cps-plugin/pull/102 ensures an eventual timeout of a build facing a `dockerd` outage ([JENKINS-37719](https://issues.jenkins-ci.org/browse/JENKINS-37719)), even without patching `docker-workflow` itself. This patch also improves upon behavior introduced in #23.
Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/29.
@reviewbybees

[JENKINS-37719] Better recovery from hangs

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

[JENKINS-34021](https://issues.jenkins-ci.org/browse/JENKINS-34021)
Amends #28 to not print misleading exceptions if a shell step has been forcibly stopped.
@reviewbybees

[JENKINS-34021] Do not overreact if a shell step is abruptly stopped

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

[JENKINS-42556](https://issues.jenkins-ci.org/browse/JENKINS-42556)
@reviewbybees

[JENKINS-42556] Make PlaceholderTask.getFullDisplayName ignore thread authentication

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

There was a reported case in which it seems that one `ExecutorPickle` (from a `parallel` branch running inside `node`) wound up scheduling the same task twice. One copy was accepted, but the other waited in the queue waiting for the one executor slot on the node, so the whole build hanged during resumption. Adding some logging which _might_ have helped with diagnosis, had this logger been enabled at `FINE`.
@reviewbybees

More logging for ExecutorPickle

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

[JENKINS-42048](https://issues.jenkins-ci.org/browse/JENKINS-42048)
Amends #30 so as to reduce log noise in the face of other bugs.
@reviewbybees

[JENKINS-42048] If there is a problem contacting the node, print one message only

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

The durable task plugin should use a different environment variable to track child processes.  Originally it overrode the JENKINS_SERVER_COOKIE variable, to ensure that the process killing done at the end of a node block would not kill tasks running in other node blocks on the same machine.  However, the killer would attempt to kill processes based on the original value of JENKINS_SERVER_COOKIE.  This means that no processes started in a node block would be killed.  With this fix, JENKINS_NODE_COOKIE is now used.  Added test to ensure that killing functionality works properly.

Fix JENKINS-28182

---

Jenkinsfile
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

The virtual thread dump applies a timeout to every step “stack frame” anyway, but if `Controller.getDiagnostics` hangs due to a broken Remoting channel, it will just print something like
```
at DSL.bat(java.util.concurrent.TimeoutException)
```
which is not as informative as it could be.
@reviewbybees

Apply a Timeout to getStatus internally

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Amending #3 for [JENKINS-45553](https://issues.jenkins-ci.org/browse/JENKINS-45553). Otherwise we tend to suck up all available `Timer` threads, causing various problems such as `copyLogs` starvation (pending JENKINS-38381).
@reviewbybees

Amending JENKINS-34542 fix for JENKINS-45553

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

See [JENKINS-36013](https://issues.jenkins-ci.org/browse/JENKINS-36013). 
For this I've not limited this to EphemeralNodes because (for example) Docker slaves may not implement EphemeralNode but may exhibit the same "once it's gone it ain't coming back" behavior.  
However I did add a boolean to track if the slave is ephemeral so that goes into the logs.

Fix [JENKINS-36013] by adding a timeout if waiting to resume on unknown node

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

Per comment here, immediately failing builds with an ExecutorPickle that depends on an EphemeralNode is not safe to do, due to the Swarm Plugin.   Documented [in the JIRA comments](https://issues.jenkins-ci.org/browse/JENKINS-36013?focusedCommentId=311834&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-311834).
So, I am restoring my original behavior (apply a timeout in all cases).  Can't remove the new field, though.
@reviewbybees CC @jglick

Make ExecutorPickle wait on EphemeralNodes when trying to resume, restoring original behavior of fix to JENKINS-36013

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java

Analogous to #44. Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/46.
@reviewbybees

Use a dedicated thread pool rather than Timer.get for DurableTaskStep.Execution.check

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Has been flaky in the past; also reared its ugly head in https://github.com/jenkinsci/workflow-api-plugin/pull/54, for which see discussion. Anyway this test is not running a shell script, nor running on a slave, so it is pretty misleading. What it _once_ tested, I can no longer recall, only that the interesting aspect of it was already pulled out long ago.
@reviewbybees

Deleting buildShellScriptOnSlaveWithDifferentResumePoint

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java

I noticed this while looking through the log of a failed build:
> after waiting for 300,000 ms because we assume unknown Node 300,000 is never going to appear!
@reviewbybees

Update index in log message to show the node name

---

.mvn/extensions.xml
Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep/help-encoding.html
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

[JEP-206](https://github.com/jenkinsci/jep/blob/master/jep/206/README.adoc)
Extracted from #21. Downstream of https://github.com/jenkinsci/durable-task-plugin/pull/61. Also downstream of https://github.com/jenkinsci/workflow-job-plugin/pull/89 for testing, but really as a user you want to update `workflow-job` as well, unless your master happens to be running in UTF-8.

[JEP-206] Gather command output in a local encoding

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

[JENKINS-41854](https://issues.jenkins-ci.org/browse/JENKINS-41854) affects my production Jenkins servers at least once a month. My only recourse is to restart Jenkins, which rehydrates the `FilePath` as described in the bug. Between the time that I hit the bug and the time I restart Jenkins, in-use workspaces are handed out to new jobs, causing both jobs to fail. I provided a detailed write-up of my experiences in [JENKINS-50504](https://issues.jenkins-ci.org/browse/JENKINS-50504), which I have now marked as a duplicate of JENKINS-41854 (I didn't know about JENKINS-41854 at the time).
Work towards fixing the bug by writing a reproducible test case. This test case focuses on highlighting the two failure modes described in the bug:
- If an agent is disconnected and reconnected during the …

Test cases for JENKINS-41854

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

[JENKINS-52165](https://issues.jenkins-ci.org/browse/JENKINS-52165) Split out of #21. Downstream of https://github.com/jenkinsci/durable-task-plugin/pull/60. Subsumes #73. Should improve performance by switching durable task logging and exit status checking from being pull (initiated by master at intervals) to push (initiated by agent at close intervals).
@reviewbybees

[JENKINS-52165] Calling Controller.watch API

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

See [JENKINS-28822](https://issues.jenkins-ci.org/browse/JENKINS-28822).
This PR uses [Jesse's proposed fix](https://issues.jenkins-ci.org/browse/JENKINS-28822?focusedCommentId=305068&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-305068) of storing any `Throwable` passed to `Execution#stop` so that it can be passed to `StepContext#onFailure` in `Execution#exited` instead of creating a new `AbortException`.
I am concerned about causing regressions for anyone relying on the current behavior or for anyone using the workarounds posted in JENKINS-28822. I will test the latter, but any thoughts on the former are welcome.

[JENKINS-28822] Distinguish between abort and failure for durable tasks

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

See [JENKINS-53837](https://issues.jenkins-ci.org/browse/JENKINS-53837).
This fixes an issue with custom `QueueTaskDispatcher`s trying to use `getOwnerTask` as part of their dispatching logic for restarted Pipelines.

[JENKINS-53837] Associate node steps with their WorkflowJob correctly after restarts

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep/help-label.html

There were a couple of inconsistencies that were problematic...
Most notably `|` instead of `||`, but also `expr||expr`, and generally the lack of spacing around tokens, and the loss of other markup.
Afaict, the same display engine is used for both places, so I don't see any particular reason not to synchronize these two files.
Note that I'm moving the comment about the source file outside of the `<div>`, depending on the display engine, that could break everything...

Mostly sync ExecutorStep/help-label.html with AbstractProject/help-label.html

---

pom.xml

These dependencies were added by #21.

Update to non-beta versions of dependencies

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

See https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/75#discussion_r227280773.
@kutzi noticed that the previous commit hashes here were not correct. In fact, they were from a different repo: https://github.com/jenkinsci/durable-task-plugin/commit/a224295d12. A commit in this repo that demonstrates the previous behavior is 3bd3498ba3, and I just confirmed locally that if you check out that commit and add the new tests, they fail as described. Maybe pointless to reference commits in the first place, since it probably isn't useful to anyone, but it won't hurt either.
@reviewbybees

Fix commit hashes in test comments

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Disabling #63 to buy some time until I can fix some acknowledged issues (mainly [JENKINS-54133](https://issues.jenkins-ci.org/browse/JENKINS-54133) and waiting for the maintainer on [JENKINS-54081](https://issues.jenkins-ci.org/browse/JENKINS-54081)) and properly investigate some reported issues which are likely linked ([JENKINS-54073](https://issues.jenkins-ci.org/browse/JENKINS-54073) and [JENKINS-53888](https://issues.jenkins-ci.org/browse/JENKINS-53888)). Complements https://github.com/jenkins-infra/update-center2/pull/247. https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/74 is still needed promptly since that seems to be independent.
Note that this retains watch mode in tests, to continue to enforce coverage in this plugin and in any other pkugins which currently have a …

[JENKINS-52165] Disable watch mode by default for now

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

As discussed in https://github.com/jenkinsci/workflow-api-plugin/pull/81.

Put the onus on remote code to PrintStream.flush

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Based off of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/19.
Implements [JENKINS-54356](https://issues.jenkins-ci.org/browse/JENKINS-54356)
The node API currently shows run details for freestyle builds, but not pipeline builds.

[JENKINS-54356] Add to node API for pipeline builds.

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Analogous to https://github.com/jenkinsci/durable-task-plugin/pull/86. #81 (amended to check `USE_WATCHING`) would be preferable, but this should be easier to get merged.

Shut down threadPool when Jenkins shuts down

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Studying [JENKINS-54133](https://issues.jenkins-ci.org/browse/JENKINS-54133). ~Safe to merge, but does not do anything at the moment.~

[JENKINS-54133] Document remote console note behavior in test

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

ShellStepTest#remoteConsoleNotes was failing in the [current CI build of master](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fworkflow-durable-task-step-plugin/detail/master/67/tests) after the buffering PR was merged.
This PR fixes the failure by adding overrides of `flush` and `close` to the `LineTransformationOutputStream` used in the test.

Add missing overrides to fix ShellStepTest#remoteConsoleNotes

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep/help-label.html
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

See [JENKINS-55410](https://issues.jenkins-ci.org/browse/JENKINS-55410).
I've added an new Attribute "label" to the durable steps, so that this is displayed within the pipeline steps view and blue ocean views instead of the technical Name "Windows Batch Script" or "Linux Shell script". We have got a lot of this and it is very hard to find the right one. 
With this labels this step can now display the real domain specific information for example "build manual" "copy driver files" etc. This makes the pipeline views very more comfortable to use.

[JENKINS-55410] Added label attribute for documentation and clarity in jenkins views

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

I have been seeing a lot of inexplicable build failures on ci.jenkins.io of the form
<details>
<summary>Stack trace</summary>
```
[Pipeline] End of Pipeline
GitHub has been notified of this commit’s build result
java.nio.channels.ClosedChannelException
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from …
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
at hudson.remoting.Request.call(Request.java:202)
at hudson.remoting.Channel.call(Channel.java:954)
at hudson.FilePath.act(FilePath.java:1072)
at hudson.FilePath.act(FilePath.java:1061)
at hudson.FilePath.exists(FilePath.java:1581)
at jenkins.branch.WorkspaceLocatorImpl.load(WorkspaceLocatorImpl.java:218)
at jenkins.branch.WorkspaceLocatorImpl.locate(WorkspaceLocatorImpl.jav …
```

Display any Computer.terminatedBy in the build log

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Besides the original discussion in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/84#discussion_r227798017, I found that watch mode was being activated in JFR “serverless” builds, including Jenkins X in `--prow` mode, due to [this questionable behavior](https://github.com/jenkinsci/jenkinsfile-runner/blob/6ca2605ea48a4c186ed48d16dcbb5db8551b5b54/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java#L654-L655). Probably less surprising to enable watch mode only when tests explicitly ask for it.
I considered making some of these test suites `Parameterized` but they were already pretty long-running and it looked complicated: some tests only make sense in watch mode or vice-versa, so was not sure whether this would be desirable.

[JENKINS-52165] Do not enable watch mode automatically in tests

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

See [JENKINS-46507](https://issues.jenkins-ci.org/browse/JENKINS-46507).
User investigation into some cases of spuriously interrupted builds shows that slow filesystem performance during these remote calls appears to cause them to take a large amount of time to complete. 
I am waiting for more feedback to see if we should bump the default timeout (right now the user investigating the issue is testing with a 10-minute timeout which seems a little too long for most cases), but I think it would be helpful to allow users to increase this timeout by system property if necessary.
@reviewbybees

[JENKINS-46507] Allow timeouts for remote calls in DurableTaskStep to be configured via system property

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Forgot to update durable-task in #95, but I just released 1.29 so might as well update it now.
I also added `-Djava.awt.headless=true` to test code that launches processes to prevent it from stealing focus on macOS similarly to jenkinsci/jenkins-test-harness#105.

Update durable-task and prevent tests from stealing focus

---

Jenkinsfile
pom.xml

For Java 11 readiness, apply recommended configuration:
https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime
And fixing what was revealed through this.

Java 11 readiness: build on recommended configurations

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Not sure how long this has been broken; I assume it is related to JEP-210 in that the issue is a `TaskListener` per step.
Despite https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/85 this fails with or without watch mode. Calling `flush()` on the stream does not suffice because `LineTransformationOutputStream` (as used in `BindingStep` and many other places) does not then `forceEol`. This fixes the test in default poll mode, though it makes me nervous because I would need to research whether per-step listeners may safely be closed:
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java b/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
index 1f8ca2b..3162ebc 100644
--- …
```

Reproduced a problem with shell output missing a final newline wrapped in a LineTransformationOutputStream

---

pom.xml

Amends #102 to use an actual LTS version, not just the baseline, in case this has some effect on update site calculations (weekly vs. LTS).

Use an LTS version

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

Improved behavior for one subcase of [JENKINS-49707](https://issues.jenkins-ci.org/browse/JENKINS-49707), that a disconnected agent is actually removed from Jenkins configuration for whatever reason. We assume that it is not going to be readded (under the same name), so there is no point in waiting for it to reconnect. ~The one exception that I know of is that a Swarm agent [will remove itself upon disconnect](https://github.com/jenkinsci/swarm-plugin/blob/796a04914e986f0fe6ab720e2cc95169831251dc/plugin/src/main/java/hudson/plugins/swarm/SwarmSlave.java#L89) but [might readd itself later](https://github.com/jenkinsci/swarm-plugin/blob/796a04914e986f0fe6ab720e2cc95169831251dc/plugin/src/main/java/hudson/plugins/swarm/PluginImpl.java#L219), so this might break cross-disconnect durability of …

[JENKINS-49707] (part): Fail the build if an agent has been removed

---

src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't consistently use the script security sandbox. Always using the script security sandbox makes the tests consistent with each other, and it's also a more realistic environment given that the script security sandbox should always be enabled in production. In this change, I replaced any usages of the deprecated single-argument constructor for `CpsFlowDefinition` with usages of the non-deprecated two-argument constructor, passing in `true` as the second argument in order to always enable the script security sandbox.

Consistently use sandbox for CpsFlowDefinitions

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Fixing the test from #103, strengthening it in the process. Taking on some urgency since after @Vlatombe’s https://github.com/jenkinsci/kubernetes-plugin/pull/552, this problem would affect any `sh` step in a Kubernetes agent which prints output without a trailing newline (no longer limited to that minority of builds which deliberately use secrets).

Final line of shell output without newline lost when using LineTransformationOutputStream-based decorators

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`User.get(java.lang.String)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#get-java.lang.String-) states: "This method is deprecated, because it causes unexpected `User` creation by API usage code and causes performance degradation of used to retrieve users by ID. Use [`getById(java.lang.String, boolean)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#getById-java.lang.String-boolean-) when you know you have an ID."
- The documentation for [`ACL.impersonate(org.acegisecurity.Authentication, java.lang.Runnable)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-java.lang.Runnable-) states: "use try with resources and …

Remove usages of deprecated APIs

---

pom.xml

Cleanup from #112 after https://github.com/jenkinsci/plugin-pom/pull/221.

plugin-pom was released

---

Jenkinsfile

Trying to fix CI issues (for example in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/115). It doesn't look like this plugin's tests use Docker, but they might be sensitive to user/permission changes in the ACI agents, so we'll see if the build passes.

Use ACI agents to avoid disk space issues in CI builds

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

See [JENKINS-58900](https://issues.jenkins-ci.org/browse/JENKINS-58900).
The problem is that you get a `MissingContextVariableException` where you would expect to get some kind of connection-related exception (seen on some builds of Jenkins core on ci.jenkins.io where the Windows agent apparently disconnected but the error in the logs was a `MissingContextVariableException`). I think this is a side effect of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/101 ([JENKINS-41854](https://issues.jenkins-ci.org/browse/JENKINS-41854)), but I haven't investigated enough to know for sure. If so, maybe fixable by throwing some kind of exception instead of just logging here: https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/5840b563c6c0cd9b7f721bcaff55e4b005be234 …

[JENKINS-58900] Improve error messages for agent disconnections inside of node

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

After upgrading `workflow-durable-task-step` from 2.31 to 2.32 in `workflow-cps-global-lib-plugin`, `LibraryMemoryTest#loaderReleased` starts failing with the following stack trace:
```
[ERROR] loaderReleased(org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest)  Time elapsed: 1.561 s  <<< ERROR!
java.lang.NullPointerException
at org.netbeans.insane.live.Path.getField(Path.java:146)
at org.netbeans.insane.live.Path.toString(Path.java:140)
at org.netbeans.insane.live.Path.toString(Path.java:138)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at java.util.AbstractMap.toString(AbstractMap.java:559)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at …
```

Release node body reference when finishing a PlaceholderTask

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellCoreScriptStep.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellCoreScriptStep/config-details.jelly
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellCoreScriptStep/help-script.html

downstream of https://github.com/jenkinsci/durable-task-plugin/pull/111
Hmm, should I add docker fixture or testcontainers or hope that our Windows server 2019 have pwsh?

add pwsh step

---

CHANGELOG.md
README.md
pom.xml

Migrating CHANGELOG from wiki to github
adding README

Migrate wiki

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

https://github.com/jenkinsci/jenkins/blob/cc27faa48d8c5a0cf421a5d648231b506391c2eb/core/src/main/java/hudson/model/Queue.java#L2267-L2270 is `final` so we may as well allow it to use rich text. Useful in conjunction with https://github.com/jenkinsci/jenkins/pull/4616.

Use CauseOfBlockage.print rather than Queue.Item.why

---

.mvn/maven.config
Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

After feedback from @dwnusbaum in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/135#discussion_r459644019, this is now a much simpler implementation.
Install https://plugins.jenkins.io/generic-environment-filters/ 1.1 or newer, and configure any of the global filters it provides in the global configuration.
* The easiest to test is "Set environment variable" as it just adds a new environment variable.
* The most comprehensive test case is "Filter environment variables..." as that allows the definition of job name exclusions, and can be configured to only apply to certain build steps. Both features work with this PR, although the latter is a bit messy because freestyle and pipeline steps have similar names, and show up in the same list here. That's just a …

[JENKINS-62014] Add support for global build step env var filters

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

when using the generator it would return `powershell label: '', script: 'test'`

fix label in step generator

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Replacing the deprecated FlowScanningUtils.
See:
https://github.com/jenkinsci/workflow-api-plugin/blob/f21a0577338eecb418d9f354de600a1a509e84f9/src/main/java/org/jenkinsci/plugins/workflow/graphanalysis/FlowScanningUtils.java#L113-L124

Use non-deprecated lazily evaluated iterateEnclosingBlocks

---

CHANGELOG.md

The casing in the documentation is incorrect which leads to usage issues if not caught. 
It should be `timeoutForNodeMillis` and not `timeOutForNodeMillis` where the "out" in "timeout" is capitalized incorrectly. 
Ref: https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/104/files#diff-ade2fcbe1968df3e789f63a80424f622R71

Match casing of timeoutForNodeMillis to code

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

See [JENKINS-63486](https://issues.jenkins.io/browse/JENKINS-63486). Amends #126.
[JENKINS-63868](https://issues.jenkins.io/browse/JENKINS-63868) was fixed in recent versions of Jenkins core, but it will still log a warning every time this code throws an exception, so we should change this code anyway.
I added a regression test in 2c1da66, but I have not attempted to reproduce the problem or test the fix on a real Jenkins instance.

[JENKINS-63486] Use ACL.SYSTEM in PlaceholderTask.getOwnerTask as before JENKINS-60389

---

Jenkinsfile
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

When running Jenkins versions > 2.65, the `ExecutorStepTest.reuseNodesWithSameLabelsInDifferentReorderedStages` test will fail.
This is due to changes in `LoadBalancer`  that were done in 2.66 here: https://github.com/jenkinsci/jenkins/pull/5028
Added a note to indicate this in the test code.

failing ExecutorStepTest in jenkins versions > 2.65

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/resources/index.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep/help.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep/help-dir.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Hello! 
This PR updates terminology for build agents in user-facing documentation, per [the glossary.](https://www.jenkins.io/doc/book/glossary/).

switch build agent terminology in user-facing documentation

---

src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`

Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

---

src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

https://www.jenkins.io/changelog/#v2.307 / https://github.com/jenkinsci/jenkins/pull/5425

Make this test compatible with Jenkins 2.307+

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Pairs with https://github.com/jenkinsci/jenkins/pull/5733; for now I am not bothering to increase the `jenkins.version`.

Implement `Queue.Executable.getParentExecutable`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

This implements the same terminology cleanup as https://github.com/jenkinsci/jenkins/pull/5425 did in core for for `NODE_NAME` variable which is set here independently of core.
This is independent of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/167 but without that PR, this one will timeout on 2.307+ (unchanged from before).
This is not expected to result in a behavior difference on Jenkins 2.306 and earlier.
On Jenkins 2.307 and later, this PR will change the behavior and make it consistent with core's (freestyle jobs etc.). This can easily be tested by using the script console to provide a custom name and label for the built-in node:
```
Jenkins.nodeNameAndSelfLabelOverride = 'mast-in'
```
----
Changelog suggestion:
* The `NODE_NAME` environment variable value set …

Change NODE_NAME for the built-in node based on its self label

---

pom.xml

Noticed in https://github.com/jenkinsci/bom/pull/640/checks?check_run_id=3626534874
cc @jglick @basil @car-roll

Fix incrementals in PCT

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

additional test cleanup to support the terminology changes in 2.307
downstream of #168

make additional tests compatible with Jenkins 2.307

---

Jenkinsfile

This reverts commit fee3af9f1c5a9c0519e80e64750d0d2f76a1223e.
`ExecutorPickleTest.canceledQueueItem` has been consistently failing on the windows CI instances since the change from `useAci` to `useContainerAgent`. Local builds on my windows machine have been passing. Reverting this commit to see if this was the issue.

Revert "Remove deprecated config (#172)"

---

Jenkinsfile

This PR is a tentative to study the behavior underlined in #173 / #172 (changing a pipeline library parameter that made a test unit to fail)

chore: revert back to 'useContainerAgent' for CI pipeline

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/47#discussion_r134517658
In https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/65a4f98c89953d9655a02d0de591af24bf300715/src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java#L141-L144
Before:
```
[p #1] ERROR: Killed hudson.model.Queue$BuildableItem:ExecutorStepExecution.PlaceholderTask{runId=p#1,label=slave0,context=CpsStepContext[3:node]:Owner[p/1:p #1],cookie=1f900f85-0501-4f30-83d9-4a8a9ed1f70a,auth=null}:3 after waiting for 15,000 ms because we assume unknown Node slave0 is never going to appear!
```
After:
```
[p #1] ERROR: Killed part of p #1 after waiting for 15,000 ms because we assume unknown Node slave0 is never going to appear!
```

Nicer build log message when `ExecutorPickle` fails to resume

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java

Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/473. Further refines #175 to use a specific `CauseOfInterruption` introduced in #104 for a related reason.
Before:
```
Resuming build at … after Jenkins restart
Waiting to resume part of p #1: ‘Jenkins’ doesn’t have label ‘slave0’
Waiting to resume part of p #1: ‘Jenkins’ doesn’t have label ‘slave0’
Waiting to resume part of p #1: ‘Jenkins’ doesn’t have label ‘slave0’
Waiting to resume part of p #1: ‘Jenkins’ doesn’t have label ‘slave0’
Waiting to resume part of p #1: ‘Jenkins’ doesn’t have label ‘slave0’
[Pipeline] End of Pipeline
ERROR: Killed part of p #1 after waiting for 15,000 ms because we assume unknown Node slave0 is never going to appear!
Finished: FAILURE
```
After:
```
Resuming build at … after Jenkins restart …
```

Make `ExecutorPickle` add `RemovedNodeCause`

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Proves that #170 is necessary to retain compatibility with some rare use cases after https://github.com/jenkinsci/jenkins/pull/5880: for example, Pipeline code coverage without https://github.com/jenkinsci/code-coverage-api-plugin/pull/245 or https://github.com/jenkinsci/cobertura-plugin/pull/130.

Demonstration that implementing `getParentExecutable` is necessary

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java

See https://github.com/jenkinsci/jenkins/pull/5934.

`ExecutorPickle` should not reschedule anything until after `Queue.load`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

While testing Jenkins in various backup and restore scenarios, we ran into a case where the Jenkins queue contained a `ExecutorStepExecution.PlaceholderTask` whose associated build was already complete, causing the task to sit in the queue forever. We are not sure how this happened or how to reproduce it, but this PR adds a test that reproduces the same symptoms that may be useful for future investigation.
I did some experimentation to see if the issue could be fixed, and something like this does fix it but does not seem like the best approach:
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java b/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
index c81bf0c..64ca128 100644
--- …
```

Recover gracefully when a `PlaceholderTask` is in the queue but the associated build is complete

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

See [JENKINS-67351](https://issues.jenkins.io/browse/JENKINS-67351) and https://github.com/jenkinsci/workflow-api-plugin/pull/188. Amends https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/185.
One of the stack traces related to JENKINS-67351 (from the jenkinsci-users mailing list) indicated that a build being accessed in `PlaceholderTask.getCauseOfBlockage` was not yet loaded because `FlowExecutionList$ItemListenerImpl.onLoaded` had not executed yet. I did not think this was possible in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/185#discussion_r762246581, and we do not want to be loading Pipelines while the queue lock is held in normal scenarios.

[JENKINS-67531] Do not load Pipelines during PlaceholderTask.getCauseOfBlockage in normal scenarios

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Test introduced in #177 begins failing after https://github.com/jenkinsci/jenkins/pull/5885 and is rendered meaningless by that cleanup. Test coverage from #170 remains.

Deleting obsolete `ExecutorStepTest.accessPermittedOnlyFromCurrentBuild`

---

pom.xml

…where superseded by `bom` or `plugin-pom` updates.

Removing explicit version overrides

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Reverts #188 and #185 due to problems in https://github.com/jenkinsci/workflow-api-plugin/pull/188 (see https://github.com/jenkinsci/workflow-api-plugin/pull/188#issuecomment-1013382364) which have no obvious fix and so require the `workflow-api` PRs to be reverted.  https://github.com/jenkinsci/workflow-api-plugin/pull/188 introduced an API required here after #188, but that API will be removed once the workflow-api PRs are reverted, so we need to revert the PRs here as well.
These fixes were generally expected only to apply to uncommon scenarios related to disaster recovery (although they apparently also mattered for regular usage of ci.jenkins.io as mentioned in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/185#issuecomment-999703045), so I think it is ok to …

Revert fixes related to JENKINS-67351 and JENKINS-67164

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

See [JENKINS-68080](https://issues.jenkins.io/browse/JENKINS-68080). I have discovered that the Pipeline: Nodes and Processes tests that enable watch mode consistently hang on Java 17. The default pull mode passes Java 17 tests. To unblock Java 17 testing, this PR skips such tests when running on Java 17. This is a temporary workaround. When JENKINS-68080 is resolved, this workaround can be deleted. I have verified in jenkinsci/bom#935 that with this PR Java 17 tests pass (by skipping the watch mode tests).

[JENKINS-68080] Temporarily disable push mode tests on Java 17+

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Fixes tests skipped in #209.
https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/bb7ad076d27b281f6213e5571719cc01a729c946/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L697-L702 is the problem
```
hudson.remoting.ProxyException: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.io.OutputStream java.io.FilterOutputStream.out accessible: module java.base does not "opens java.io" to unnamed module @… [master]
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) [master]
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) [master]
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) [master]
at …
```

[JENKINS-68080] `DurableTaskStep.HandlerImpl.printStreamDelegate` requires `--add-opens`

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/428. Preparation for #180.

[JENKINS-26398] Use standard `JenkinsRule.createSlave` plus new `InboundAgentRule`

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

calling `setLabels` on an agent will not persist the node.
in older versions of Jenkins the tests would be less flaky as adding any
Node would cause all labels to be re-evaluated, so when creating a few
agents and adding labels in a loop the last one created would at least
deterministically ensure that all previous agents labels where correct.
However since 2.332 (https://github.com/jenkinsci/jenkins/pull/5882)
only labels part of a node added or removed would be updated, and when
creating the agents they where created without labels, which where added
later.
This caused tests to be flaky depending on when the periodic
`trimLabels` was called (or at least on other timing related things)
THis was discovered by enabling a loggerrule for hudson.model.queue and
observing that the builds would …

Deflake and speed up parts of `ExecutorStepTest`

---

pom.xml

https://issues.jenkins.io/browse/JENKINS-68727
Following up https://github.com/jenkinsci/workflow-api-plugin/pull/226 so that #226 is offered only to 2.332.x+ users.

[JENKINS-68727] Require 2.332.x

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

@dduportal reports a situation where a stale `PlaceholderTask` sits in the queue and apparently cannot be canceled from the GUI (see also #241).

Warn when `Queue.cancel` calls fail

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentOfflineException.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorConditionTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/RetryExecutorStepTest.java

Make `retry(count: …, conditions: [agent()])` handle more cases:
* `Unable to create live FilePath…` which is observed sometimes before an agent is even used for the first time. (https://github.com/jenkins-infra/helpdesk/issues/2984#issuecomment-1178022133)
* The queue item for a `node` block was cancelled. While this _could_ be something that happened due to manual administrator intervention, typically it is a side effect of the cloud killing things off. `KubernetesAgentErrorCondition` (https://github.com/jenkinsci/kubernetes-plugin/pull/1190) already handles this because when a pod is removed, the cloud tried to clean up by removing the agent from the controller’s list of nodes (already handled) _and_ cancelling any outstanding queue items associated with it, but the order is tricky to …

[JENKINS-49707] `AgentErrorCondition` improvements

---

src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

Rather than "master" use "controller"
Rather than "slave" use "agent"
~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Make a comment more inclusive

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java

Amends #231.
Normally `AgentErrorConditionTest.retryNodeBlockSynch` retries after an exception like this (line numbers adjusted for 2.346.x), where the cause is a `ClosedChannelException`:
```
java.nio.channels.ClosedChannelException
at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:240)
at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:177)
at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngin …
```

Handle `ChannelClosedException` in `AgentErrorCondition`

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/250#discussion_r924871316 now would fail like
```
Expected: an array containing a string containing "(some other text)"
but: mismatches were: [was "Start of Pipeline", was "node", was "node block", was "isUnix", was "sh (Step with label)"]
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.jenkinsci.plugins.workflow.steps.durable_task.ShellStepTest.label(ShellStepTest.java:366)
```

Improve `ShellStepTest.label` with Hamcrest

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorConditionTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/124, and https://github.com/jenkinsci/workflow-cps-plugin/pull/570 to be effective.
https://github.com/jenkins-infra/helpdesk/issues/3031#issuecomment-1175343746 noted earlier in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180#discussion_r914058932. If you have
```groovy
retry(2) { // no conditions: […]
node('remote') {
sh 'work
}
}
```
and the agent is removed, the block was surprisingly not retried. This is because `actualInterruption` defaults to true for compatibility in https://github.com/jenkinsci/workflow-step-api-plugin/pull/51 and `BodyExecution.cancel(CauseOfInterruption...)` does not override that.

[JENKINS-49707] `retry` without conditions should handle node removal

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextTest.java

[JENKINS-69936](https://issues.jenkins.io/browse/JENKINS-69936): amending https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180#discussion_r966433158 by ignoring a `FilePathRepresentation` which does not match the node name of the nearest enclosing `ExecutorStepDynamicContext`. Currently `DelegatedContext` lacks an exposed notion of depth, so if both contextual objects are present at different depths, we cannot tell which is deeper.

[JENKINS-69936] Handle mixture of nested `node`, `dir`, & `ws`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextTest.java

#270 handled the common case that the nested `node` blocks actually ran on distinct agents. It is however possible (when agents have multiple executors) for the nested `node` to run in a new workspace on the _same_ agent: [JENKINS-70528](https://issues.jenkins.io/browse/JENKINS-70528). Trying to extend the earlier fix to handle this case just breaks `ws` and `dir` steps.

[JENKINS-70528] Reproducing `FilePathDynamicContext`-related bug in test

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/PushdStep.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/PushdStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/PushdStep/help-path.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/PushdStep/help.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/PushdStepTest.java

https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/86#discussion_r289906309 https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/291#issuecomment-1432225010
Testing:
* Run 2.387 on a fresh userdir. Install `workflow-{job,cps,basic-steps,durable-task-step` and `pipeline-input-step`. Configure and start a project
```groovy
node {
sh 'pwd'
dir('subdir') {
sh 'pwd'
input 'proceed?'
sh 'pwd'
}
sh 'pwd'
}
```
* Install a snapshot build of this PR and restart.
* Confirm that the running build is still running.
* Run another project and confirm that it works, though `DSL` prints a warning:
```groovy
node {
sh 'pwd'
dir('foo') {
sh 'pwd'
}
sh 'pwd'
}
```
* Check **Pipeline Syntax** to see that `dir` is offered, once, and the help button indicates that it comes from this …

Moving `PushdStep` here from `workflow-basic-steps`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/PushdStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextTest.java

[JENKINS-70528](https://issues.jenkins.io/browse/JENKINS-70528)
https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/291#issuecomment-1432225010 subsuming #293

[JENKINS-70528] `node` / `dir` / `node` on same agent sets PWD to that of `dir` rather than `@2` workspace

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep/help-dir.html

[JENKINS-41219](https://issues.jenkins.io/browse/JENKINS-41219) especially after https://github.com/jenkinsci/pipeline-stage-step-plugin/pull/94.

[JENKINS-41219] Do not refer to now-removed `concurrency` param to `stage`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Implements the API introduced in https://github.com/jenkinsci/jenkins/pull/7599, for now without requiring a newer core dep.

Implement `SubTask.getOwnerExecutable`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Observed during a build of https://github.com/jenkinsci/bom/pull/1832. @dduportal et al., any interest in testing this?

[JENKINS-60507] Eventually cancel `node` blocks in anomalous status

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Not locally reproducible, but have observed in PCT
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepTest.lambda$queueItemAction$20(ExecutorStepTest.java:608)
```
I am guessing this is some sort of race condition, in which case waiting a bit might help.

Trying to deflake `ExecutorStepTest.queueItemAction`

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

The plugin no longer supports Jenkins versions as old as 2.265, so the conditional will always evaluate to true.
Automated tests pass on Linux with Java 11.

Remove outdated Jenkins version test conditional

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/RealShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

[JENKINS-52165](https://issues.jenkins.io/browse/JENKINS-52165): the performance benefits seem important. Have not yet tried to measure impact on (controller) CPU or Remoting channel bandwidth, but can use inotify to verify this allows a long-running `sh` step with copious output to only write to `log` (and maybe `log-index`), whereas in currently default pull mode there are constant writes to `program.dat` (via an atomic temp file) due to https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/6f24fa9eb65bc86c5d34718990f90db968f0003e/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L599-L601 which would otherwise be limited to step transitions.
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/294 and …

[JENKINS-52165] Stabilize and better test `USE_WATCHING`

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Likely pointless to even try to record `sh` step output when the build is so broken that `TaskListener` is not available from the `StepContext`! See https://github.com/jenkinsci/workflow-api-plugin/pull/298.

Do not even try to use `LogTaskListener`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution/PlaceholderTask/PlaceholderExecutable/executorCell.jelly

See https://github.com/jenkinsci/jenkins/blob/4c5e4f86d1fb3bce5d027446e12259c7edcac27f/core/src/main/resources/lib/hudson/buildProgressBar.jelly#L29.
In practice this did not matter because the Jelly template only ever used `build.url` in this case, which is the same between `PlaceholderTask` and `PlaceholderExecutable`, but it causes problems with some changes I am proposing upstream in https://github.com/jenkinsci/jenkins/pull/8321 where we actually need to find the associated `Run`, see [this comment]( https://github.com/jenkinsci/jenkins/pull/8321/files#r1289340587) in particular.
Tested manually.
```[tasklist]
```

`build` attribute for `buildProgressBar` should be a `Queue.Executable`, not a `Queue.Task`

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Pairs with https://github.com/jenkinsci/durable-task-plugin/pull/187. I noticed a flake in `ExecutorStepTest.contextualizeFreshFilePathAfterAgentReconnection[watching=true]`: the test timed out, and the log included
```
WARNING: org.jenkinsci.plugins.durabletask.FileMonitoringTask$Watcher@… giving up on watching …/dumbo/workspace/demo@tmp/durable-…
java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Long.parseLong(Long.java:702)
at java.base/java.lang.Long.parseLong(Long.java:817)
at org.jenkinsci.plugins.durabletask.FileMonitoringTask$Watcher.run(FileMonitoringTask.java:622)
```
I do not have a clear hypothesis as to why `lastLocation` was empty; perhaps a half-written file …

`lastLocation` testing

---

src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

Despite `Label.parse` returning a `TreeSet`, `Node#getAssignedLabels` returns a `Set` and `NODE_LABELS` doesn't make any promise to return a sorted set.
So better match labels unordered.
```[tasklist]
```

EnvWorkflowTest#isNodeNameAvailable robustness

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Hoping to track down a test failure in @cloudbees which shows a build being aborted with `QueueTaskCancelled` but not why. The other plausible path is https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/68be217043e3a52a25254c3c433f71e601f043f3/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java#L113-L115 which already does fine logging.

Fine logging with stack trace when queue item cancelled

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep2Test.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Working on the same test as in #353, I found a (locally unreproducible) case where it appears that `Queue.cancel` from `PlaceholderTask.Callback.finished` triggered `CancelledItemListener`. `PlaceholderTask.stopping` was designed to prevent exactly this; the fact that it did not suggests that there are multiple `PlaceholderTask`s involved. As in #344, the root design flaw is that there is mutable state in `PlaceholderTask` yet it is difficult to ensure Java object identity here. So here I am moving the `stopping` field to transient global state (`RunningTasks`). I am also restoring `cookie` to its original purpose of an actual environment variable value used for nothing more than killing off stray background processes at the end of the block; and using `StepContext` as the primary key …

Simplified `PlaceholderTask`

---

Jenkinsfile
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep2Test.java

The test motivating #354 flaked again. From the logs, the cause is clear enough: the `RunningTask` was removed before `Queue.cancel` was called, so `CancelledItemListener` was still active. (I have no idea how to reproduce this scenario, leading to the build being aborted.)

`PlaceholderTask.Callback.finished` did not correctly suppress `CancelledItemListener`, and `willContinue` was unreliable

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

#299 continued. https://issues.jenkins.io/browse/JENKINS-60507?focusedId=445029&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-445029

[JENKINS-60507] Extra diagnostic log

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Regression in #372 caught by PCT on `kubernetes`:
```
java.lang.AssertionError: 
routine build should not issue warnings
Expected: an empty iterable
but: ["org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$RemovedNodeListener.cancelOwnerExecution: null"]
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesPipelineTest.runInPod(KubernetesPipelineTest.java:245)
```
after
```
5.274 [run In Pod #1] [Pipeline] // node
5.274 [run In Pod #1] [Pipeline] }
5.274 [run In Pod #1] [Pipeline] // podTemplate
5.274 [run In Pod #1] [Pipeline] semaphore
5.274 [run In Pod #1] [Pipeline] End of Pipeline
5.297 [run In Pod #1] Finished: SUCCESS
5.300 [id=3097]	FINE	o.c.j.p.k.KubernetesCloud#connect: Connected to …
```

`RemovedNodeListener.cancelOwnerExecution` can be noisy

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

I need to capture the current state of ExecutorStepExecution including this field from another plugin for a HA use case, so I need to expose this field.

Expose `ExecutorStepExecution#getEnclosingLabel`

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

In many cases when restoring a build into another K8s cluster using a very lossy backup of the filesystem, via EFS Replication (which does not guarantee snapshot semantics), there is some sort of problem with metadata, which prevents `node` block retry from recovering automatically. (Prior to https://github.com/jenkinsci/kubernetes-plugin/pull/1617 it did not work even if metadata was perfect.) Sometimes there is a missing `program.dat`, sometimes a corrupted log file, sometimes a missing `FlowNode`, etc.
But in many of these cases ([CloudBees-internal reference](https://cloudbees.atlassian.net/browse/BEE-53259)), the log seems fine and the flow nodes seem fine, yet for reasons I cannot easily follow because `program.dat` is so opaque, the `node` block seems to have received an …

Extending `AnomalousStatus` to also kill `sh` steps

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

I'm hitting a few failures running the existing tests on MacOS due to behavioural differences with linux.

Fix running tests on MacOS

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextRJRTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecutionRJRTest.java

This covers a case where a queue item for a node was filed, then the controller shut down without going through clean up.
Because of that, the queue wasn't saved, and when the controller restarts, the queue item is gone.
This modifies the behaviour of `ExecutorStepExecution#onResume` to detect this condition and re-schedule a new queue item if needed.
See provided unit test.

Build fails to resume if controller crashes before queue is saved

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Observed an NPE randomly in a controller under heavy load.

Handle null `controller` in `DurableTaskStep.Execution.getStatus`

---

Jenkinsfile

Too much parallelism appears to be causing test flakiness.

Remove `forkCount`

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Not changing production code, just adapting tests to the most recent Windows agents attached to ci.jenkins.io
Passes on my Windows computer and on ci.jenkins.io

Sleep longer in the Windows tests

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java

Amending #231 to pick up https://github.com/jenkinsci/remoting/pull/657.

Use standard `Channel.isClosedChannelException`
