src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

[JENKINS-34542](https://issues.jenkins-ci.org/browse/JENKINS-34542)
@reviewbybees

[JENKINS-34542] Avoid holding the runningTasks lock while running Launcher.kill

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

[JENKINS-28240](https://issues.jenkins-ci.org/browse/JENKINS-28240)
@reviewbybees

[JENKINS-28240] IllegalStateException from DurableTaskStep.Execution.start

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

[JENKINS-34021](https://issues.jenkins-ci.org/browse/JENKINS-34021)
Symptomatic & diagnostic fix.
@reviewbybees

[JENKINS-34021] If DurableTaskStep.Execution.listener is sometimes null

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/7 and https://github.com/jenkinsci/durable-task-plugin/pull/26 and https://github.com/jenkinsci/workflow-step-api-plugin/pull/4.
@reviewbybees

[JENKINS-31842] Thread dump improvements

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

A few cleanups in tests

---

.gitignore

Add .idea and *.iml to .gitignore

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Helped find a bug in https://github.com/jenkinsci/ant-plugin/pull/22.
@reviewbybees

Added logging allowing us to diagnose Guice injection errors

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java

[JENKINS-33511](https://issues.jenkins-ci.org/browse/JENKINS-33511)
@reviewbybees

[JENKINS-33511] Expose $WORKSPACE and $NODE_LABELS

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Added a Jenkinsfile

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep.java
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/config-details.jelly
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/help-script.html
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellStepTest.java

This pull request enables Powershell support.  Please see the related pull request into the Durable Task plugin repo: https://github.com/jenkinsci/durable-task-plugin/pull/39

[FIXED JENKINS-34581] Enabling Powershell support

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Just a test confirming there is no defect for common agent types
https://issues.jenkins-ci.org/browse/JENKINS-44521
@reviewbybees @jglick

[JENKINS-44521] - Add direct tests confirming the use-case works well

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java

[JENKINS-45553](https://issues.jenkins-ci.org/browse/JENKINS-45553)
```
"Running CpsFlowExecution[Owner[…]]" …
java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.fillInStackTrace(Native Method)
at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
- locked <0x000000078e4f1e28> (a com.google.inject.internal.ErrorsException)
at java.lang.Throwable.<init>(Throwable.java:250)
at java.lang.Exception.<init>(Exception.java:54)
at com.google.inject.internal.ErrorsException.<init>(ErrorsException.java:31)
at com.google.inject.internal.Errors.toException(Errors.java:527)
at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:801)
at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:789)
at …
```

Dropping use of Guice

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Amends #2 to improve performance as in [JENKINS-45553](https://issues.jenkins-ci.org/browse/JENKINS-45553). Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/46.
@reviewbybees

[JENKINS-45553] Use getPersistentAction to optimize JENKINS-26132

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java

See https://github.com/jenkins-infra/deprecated-usage-in-plugins/pull/7
cc @reviewbybees

Stop using jenkins.util.SystemProperties

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

[JENKINS-46738](https://issues.jenkins-ci.org/browse/JENKINS-46738)
@reviewbybees

[JENKINS-46738] Deadlock in PlaceholderExecutable

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/30.
@reviewbybees

[JENKINS-26148] Using default implementation of StepExecution.stop

---

pom.xml

Pick up https://github.com/jenkinsci/durable-task-plugin/pull/49 in our tests here.
@reviewbybees

Make sure we are testing against JENKINS-47791

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Downstream of https://github.com/jenkinsci/durable-task-plugin/pull/57.
@reviewbybees

[JENKINS-48300] Call new API to get messages about negative exit codes

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Was originally going into #85 until that got merged. See https://github.com/jenkinsci/workflow-api-plugin/pull/81.

Integration tests against buffered output

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Amends @roguishmountain’s #68 using https://github.com/jenkinsci/jenkins/pull/2999.

No need to override default impls from AccessControlled

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/BatchScriptStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

See [JENKINS-52943](https://issues.jenkins-ci.org/browse/JENKINS-52943).

[JENKINS-52943] Add descriptors for shell steps

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Refiling #78 for @orgi to test changes to the Jenkinsfile.

[JENKINS-36547] Allow node reuse for pipeline jobs

---

pom.xml

https://mvnrepository.com/artifact/org.jenkins-ci.plugins/plugin?repo=jenkins-releases

update org.jenkins-ci.plugins/plugin from 3.40 to 3.43

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/42 & https://github.com/jenkinsci/workflow-cps-plugin/pull/291. Enables test created in #70.

[JENKINS-41854] Recontextualizing FilePath on demand

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Functional test for https://github.com/jenkinsci/jenkins/pull/3955. ~Subsumes https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/101.~

[JENKINS-50504] Demonstrate effectiveness of core fix in functional test

---

README.md

See https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/123#discussion_r352491957.

Remove redundant security warnings

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

[JENKINS-60389](https://issues.jenkins-ci.org/browse/JENKINS-60389)

[JENKINS-60389] Optimization for getOwnerTask

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepTest.java

Like https://github.com/jenkinsci/jenkins/pull/4414 but for Pipeline builds.

[JENKINS-60634] Bind $WORKSPACE_TMP from the node & ws steps

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java

[JENKINS-61197](https://issues.jenkins-ci.org/browse/JENKINS-61197)
Amends #128. Compared to https://github.com/jenkinsci/jenkins/pull/4526 this is more conservative.

[JENKINS-61197] Skip $WORKSPACE_TMP for root directories

---

pom.xml

It shows `The Jenkins Plugins Parent POM Project`, see below:
Let's use the short description from https://plugins.jenkins.io/workflow-durable-task-step

Update description to be exposed in the Plugin Manager UI view

---

CHANGELOG.md
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

I am planning on releasing the plugin today.

Add release notes for 2.36

---

CHANGELOG.md

I am planning on releasing the plugin today to get #144 released.

Add release notes for 2.37

---

CHANGELOG.md

add 2.38 to changelog

---

CHANGELOG.md
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep/help-label.html

Remove usage of master, slave when possible.

[JENKINS-65398] Terminology updates

---

CHANGELOG.md

add 2.39 to changelog

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
CHANGELOG.md
README.md

enable release-drafter

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Adapts to jenkinsci/jenkins#5467.

Stop using deprecated Util#join

---

Jenkinsfile

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/168/checks?check_run_id=3661887649

Remove deprecated config

---

src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/48#discussion_r135398631

Removing dead field `ExecutorPickle.ephemeral`

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/BatchScriptStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellCoreScriptStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep.java
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep.java
src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Switch from JSR 305 to SpotBugs and add missing annotations.
----------------------------------

Add missing nullability annotations and replace JSR 305

---

.github/workflows/cd.yaml

Use Temurin instead of outdated AdoptOpenJDK. `setup-java` v3 has internal changes only.
----------------

Switch to Temurin distribution

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Slightly less general, but probably more robust, implementation.

Improve `PlaceholderTask.getACL`

---

src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellCoreScriptStep/help-script.html
src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/help-script.html

Ref: https://github.com/jenkins-infra/helpdesk/issues/2974
It might be too light, open to feedbacks.

chore: add a note linking the difference between Windows PowerShell and PowerShell Core

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/RetryExecutorStepTest.java

[JENKINS-49707] Cleanups after merge of `node` retry base PR

---

src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

Fixes label unit tests in `ShellStepTest` that were broken by https://github.com/jenkinsci/workflow-support-plugin/pull/183

update ShellStepTest to support workflow-support 827.v7ef666c4d65c

---

src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepTest.java

- Make a comment more inclusive
- Make a comment more inclusive
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

More inclusive comments - combine #220 and #221

---

pom.xml

Subsumes #263. Supersedes #266. Picks up https://github.com/jenkinsci/bom/pull/1298.

Pick up deps from newer BOM

---

Jenkinsfile
pom.xml

Supersedes #272, #273, and #276.

Bump core dep, POM, BOM

---

Jenkinsfile

https://github.com/jenkins-infra/helpdesk/issues/3931#issuecomment-1929457197

Restore Windows branch in PRs

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

https://github.com/jenkinsci/workflow-step-api-plugin/pull/197

Using `StepExecution.acceptAll`

---

pom.xml

Current plugin POM contains this change

Remove test harness override

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Migrate from deprecated methods to non-deprecated equivalents.
`mvn clean verify`

Migrate from Acegi to Spring Security

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java

Like https://github.com/jenkinsci/slack-plugin/pull/1075. This was removed by @BobDu in https://github.com/jenkinsci/json-lib/pull/81.

Remove use of `JsonSlurper`

---

src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java

https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/474#pullrequestreview-3202538591

Avoiding `StringUtils`
